# Étape de build
FROM rust:1.82.0 AS builder
WORKDIR /app
COPY . .
RUN cargo fetch
RUN cargo build --release

# Étape pour la production
FROM rust:1.82.0 AS production
WORKDIR /app
COPY --from=builder /app/target/release/sdv-api /app/sdv-api
EXPOSE 80
ENV ROCKET_PORT=80
CMD ["/app/sdv-api"]

# Étape pour le développement
FROM rust:1.82.0 AS development
WORKDIR /app
COPY . .
RUN cargo install cargo-watch
EXPOSE 8000
ENV ROCKET_PORT=8000
CMD ["cargo", "watch", "-x", "run"]