name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub (First Repo)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API Image
        run: docker build --target production -f sdv-api/dockerfile -t rustapilebretontomsdv:latest ./sdv-api

      - name: Build Web Image
        run: docker build -f sdv-web/dockerfile -t frontendlebretontomsdv:latest ./sdv-web

      - name: Tag and Push API Image
        run: |
          docker tag rustapilebretontomsdv:latest ${{ secrets.DOCKER_USERNAME }}/rustapilebretontomsdv:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rustapilebretontomsdv:latest

      - name: Tag and Push Web Image
        run: |
          docker tag frontendlebretontomsdv:latest ${{ secrets.DOCKER_USERNAME }}/frontendlebretontomsdv:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontendlebretontomsdv:latest
